// <auto-generated />
using BusStationEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusStationEF.Migrations
{
    [DbContext(typeof(EFDataContext))]
    partial class EFDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusStationEF.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Buses", (string)null);
                });

            modelBuilder.Entity("BusStationEF.Models.JorneyReport", b =>
                {
                    b.Property<int>("JorneyReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JorneyReportId"));

                    b.Property<decimal>("TotalCancealReserveCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCancealReseveCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCancealSoldCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCancealSoldCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalReserveCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalReserveCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSoldCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSoldCount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("JorneyReportId");

                    b.ToTable("JorneyReport", (string)null);
                });

            modelBuilder.Entity("BusStationEF.Models.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Journeys", (string)null);
                });

            modelBuilder.Entity("BusStationEF.Models.JourneySeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("JorneyReportId")
                        .HasColumnType("int");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("JorneyReportId")
                        .IsUnique();

                    b.HasIndex("JourneyId")
                        .IsUnique();

                    b.ToTable("JourneySeats", (string)null);
                });

            modelBuilder.Entity("BusStationEF.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JourneySeatId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JourneySeatId");

                    b.ToTable("Seat", (string)null);
                });

            modelBuilder.Entity("BusStationEF.Models.JourneySeat", b =>
                {
                    b.HasOne("BusStationEF.Models.Bus", "Bus")
                        .WithMany("JourneySeats")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BusStationEF.Models.JorneyReport", "JorneyReport")
                        .WithOne("JourneySeat")
                        .HasForeignKey("BusStationEF.Models.JourneySeat", "JorneyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStationEF.Models.Journey", "Journey")
                        .WithOne("JourneySeat")
                        .HasForeignKey("BusStationEF.Models.JourneySeat", "JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("JorneyReport");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("BusStationEF.Models.Seat", b =>
                {
                    b.HasOne("BusStationEF.Models.JourneySeat", "JourneySeat")
                        .WithMany("Seats")
                        .HasForeignKey("JourneySeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JourneySeat");
                });

            modelBuilder.Entity("BusStationEF.Models.Bus", b =>
                {
                    b.Navigation("JourneySeats");
                });

            modelBuilder.Entity("BusStationEF.Models.JorneyReport", b =>
                {
                    b.Navigation("JourneySeat")
                        .IsRequired();
                });

            modelBuilder.Entity("BusStationEF.Models.Journey", b =>
                {
                    b.Navigation("JourneySeat")
                        .IsRequired();
                });

            modelBuilder.Entity("BusStationEF.Models.JourneySeat", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
